[0KRunning with gitlab-ci-multi-runner 9.5.1 (96b34cc)
  on Shared Gitlab Runner Token (87897d2f)
[0;m[0KUsing Docker executor with image centos:6 ...
[0;m[31;1mERROR: Preparation failed: Error response from daemon: open /var/lib/docker/aufs/layers/5558eec4d49baf04e497b7440d4178a4a8347836d62ce96e55576244662baab4: no such file or directory
[0;m[32;1mWill be retried in 3s ...
[0;m[0KUsing Docker executor with image centos:6 ...
[0;m[31;1mERROR: Preparation failed: Error response from daemon: open /var/lib/docker/aufs/layers/5558eec4d49baf04e497b7440d4178a4a8347836d62ce96e55576244662baab4: no such file or directory
[0;m[32;1mWill be retried in 3s ...
[0;m[0KUsing Docker executor with image centos:6 ...
[0;m[31;1mERROR: Preparation failed: Error response from daemon: open /var/lib/docker/aufs/layers/5558eec4d49baf04e497b7440d4178a4a8347836d62ce96e55576244662baab4: no such file or directory
[0;m[32;1mWill be retried in 3s ...
[0;m[31;1mERROR: Job failed (system failure): Error response from daemon: open /var/lib/docker/aufs/layers/5558eec4d49baf04e497b7440d4178a4a8347836d62ce96e55576244662baab4: no such file or directory
[0;m